version: "3.5"

services:
  php_fpm:
      build: .
      container_name: giraffe_php_fpm
      restart: always
      working_dir: /usr/share/nginx/giraffe
      networks:
          - giraffe
      volumes:
          - ./:/usr/share/nginx/giraffe
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  nginx:
      image: nginx:1.15
      container_name: giraffe_nginx
      restart: always
      working_dir: /usr/share/nginx/giraffe
      networks:
          - giraffe
      ports:
          - "443:443"
      volumes:
          - ./:/usr/share/nginx/giraffe
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
          - ./docker/nginx/ssl/giraffe.local.crt:/etc/nginx/ssl/giraffe.local.crt
          - ./docker/nginx/ssl/giraffe.local.key:/etc/nginx/ssl/giraffe.local.key

  mysql:
      image: mysql:5.7
      container_name: giraffe_mysql
      restart: always
      networks:
          - giraffe
      volumes:
          - ./docker/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      ports:
          - "3306:3306"
      environment:
          - MYSQL_DATABASE=${DB_DATABASE}
          - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
          - MYSQL_USER=${DB_USERNAME}
          - MYSQL_PASSWORD=${DB_PASSWORD}

networks:
  giraffe:
    driver: bridge
