version: "3.5"

services:
  php_fpm:
      build: .
      container_name: warthog_php_fpm
      restart: always
      working_dir: /usr/share/nginx/warthog
      networks:
          - warthog
      volumes:
          - ./:/usr/share/nginx/warthog
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  nginx:
      image: nginx:1.15
      container_name: warthog_nginx
      restart: always
      working_dir: /usr/share/nginx/warthog
      networks:
          - warthog
      ports:
          - "443:443"
      volumes:
          - ./:/usr/share/nginx/warthog
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
          - ./docker/nginx/ssl/warthog.local.crt:/etc/nginx/ssl/warthog.local.crt
          - ./docker/nginx/ssl/warthog.local.key:/etc/nginx/ssl/warthog.local.key

  mysql:
      image: mysql:5.7
      container_name: warthog_mysql
      restart: always
      networks:
          - warthog
      volumes:
          - ./docker/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      ports:
          - "3306:3306"
      environment:
          - MYSQL_DATABASE=${DB_DATABASE}
          - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
          - MYSQL_USER=${DB_USERNAME}
          - MYSQL_PASSWORD=${DB_PASSWORD}

networks:
  warthog:
    driver: bridge
